# Generated by Django 5.2.5 on 2025-10-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_mark_score_assignment_total_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_background',
            field=models.CharField(blank=True, choices=[('FSc Pre-Medical', 'FSc Pre-Medical'), ('FSc Pre-Engineering', 'FSc Pre-Engineering'), ('ICS', 'ICS'), ('ICom', 'ICom'), ('FA', 'FA'), ('BA', 'BA'), ('BSc', 'BSc'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, choices=[('BS', 'BS / Bachelor'), ('MS', 'MS / Master'), ('MPhil', 'MPhil'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
